### PR TITLE
Drag and drop .sna and .z80 (v1) files now works

### PR DESCRIPTION
**Pull request by hippietrail**
I struggled a lot with the code. Not expecting you to accept PR as is by any stretch.

1. I think my drag and drop / pasteboard code is a mix of old and new Cocoa methods.
2. I overloaded the game load functions with a bool which is surely not best
3. I couldn't get the registered drag and drop types to work with URL type and fileURL seemed to be a string
4. since snapshot files are so tiny they should work great by registering file contents for drag and drop but that is either gone since the last major change to how the pasteboard works, or i just couldn't figure it out
5. one place in the code I noticed I'm using an `NSURL` instead of just as `URL` but trying to change it caused an endless cascade of Xcode errors I couldn't understand so gave up and left it as is

Feedback will be greatly appreciated!

The plus is that it's now easy to test .z80 loading without changing the build manually all the time. I already noticed my .z80 loader doesn't read the last 30 bytes and yours had a `<` or `>` where there should be a `<=` or `>=` on version 1 files but loads more games properly than mine. But your .z80 loader seems to have something very wrong with version 2/3 files that caused the screen to corrupt and then crash. Code looked right though. Anyway that will be easier to test now.

In theory we should be able to load .sna and .z80 files by dragging links from web browsers with only minor changes.

### CODE REVIEW

**Review by shaymanjohn — COMMENTED** [review]
I think this is generally quite neat (I've never coded drag and drop on a Mac app).

I would change a few things - you're right, we shouldn't need the 'isFromDragAndDrop' property at all.

A nicer way to do this is always pass the game url to the loader (even when the game is one in the bundle), and then all the code simplifies.

If you don't mind adding me as a contributor to your repo I'll push a new branch up there (drop-files-jw) which has the tweaks in so you can see them...

Only other things I'd change is the bit where you take the window and get the windowcontroller->contentviewcontroller - better to use a simple delegate here (again I've tweaked this in my branch)

**Comment by shaymanjohn** [comment]
> I think this is generally quite neat (I've never coded drag and drop on a Mac app).
> 
> I would change a few things - you're right, we shouldn't need the 'isFromDragAndDrop' property at all.
> 
> A nicer way to do this is always pass the game url to the loader (even when the game is one in the bundle), and then all the code simplifies.
> 
> If you don't mind adding me as a contributor to your repo I'll push a new branch up there (drop-files-jw) which has the tweaks in so you can see them...
> 
> Only other things I'd change is the bit where you take the window and get the windowcontroller->contentviewcontroller - better to use a simple delegate here (again I've tweaked this in my branch)

Actually, one more thing - I'd take the validation out of the dragging code (i.e. where you're checking for 48k snapshot size) - this should only be done in the loader. I've changed the validation to only check that the file type is in the known file types (e.g. "z80" and "sna")

**Comment by hippietrail** [comment]
I've added you as a collaborator. The only reason I used the "bool hack" was because I couldn't get the fileURL to work as a URL for some reason and since I had it as a string it wouldn't have a different signature from the existing loader. But your solution sounds much neater and something I wouldn't've been able to think of with my limited knowledge of Apple concepts.

The part where I get the contentviewcontroller from the windowcontroller probably took longer than the drag and drop code. It was very difficult to Google for. I like to learn by reading code but it also helps to read an overview of the system and there seems to be a general dearth of MacOS documentation and examples, and what there is can be for old versions of Swift or MacOS, even for Objective C, or can be for SwiftUI and too new.

Checking the file size was partly an exercise to see what I could do and partly because file extensions are often used on many different filetypes. Apple may have a standard for what to do here. I don't know, so it's all good (-: If these file formats included a signature in their header I think I would check in that function, and checking the file size was the closest I could do.

**Comment by shaymanjohn** [comment]
> I've added you as a collaborator. The only reason I used the "bool hack" was because I couldn't get the fileURL to work as a URL for some reason and since I had it as a string it wouldn't have a different signature from the existing loader. But your solution sounds much neater and something I wouldn't've been able to think of with my limited knowledge of Apple concepts.
> 
> The part where I get the contentviewcontroller from the windowcontroller probably took longer than the drag and drop code. It was very difficult to Google for. I like to learn by reading code but it also helps to read an overview of the system and there seems to be a general dearth of MacOS documentation and examples, and what there is can be for old versions of Swift or MacOS, even for Objective C, or can be for SwiftUI and too new.
> 
> Checking the file size was partly an exercise to see what I could do and partly because file extensions are often used on many different filetypes. Apple may have a standard for what to do here. I don't know, so it's all good (-: If these file formats included a signature in their header I think I would check in that function, and checking the file size was the closest I could do.



> I've added you as a collaborator. The only reason I used the "bool hack" was because I couldn't get the fileURL to work as a URL for some reason and since I had it as a string it wouldn't have a different signature from the existing loader. But your solution sounds much neater and something I wouldn't've been able to think of with my limited knowledge of Apple concepts.
> 
> The part where I get the contentviewcontroller from the windowcontroller probably took longer than the drag and drop code. It was very difficult to Google for. I like to learn by reading code but it also helps to read an overview of the system and there seems to be a general dearth of MacOS documentation and examples, and what there is can be for old versions of Swift or MacOS, even for Objective C, or can be for SwiftUI and too new.
> 
> Checking the file size was partly an exercise to see what I could do and partly because file extensions are often used on many different filetypes. Apple may have a standard for what to do here. I don't know, so it's all good (-: If these file formats included a signature in their header I think I would check in that function, and checking the file size was the closest I could do.

Ah no worries, honestly I think you're doing great - please don't take any comments as criticism - I'm a freelance iOS dev, so the Mac is also a bit of a mystery in some regards, but with experience you get to spot (and use) similar patterns across the different platforms. I've pushed my branch to your repo, have a look and see what you think.

**Comment by hippietrail** [comment]
I'm actually getting an error on line 16 of EmulatorImageView.swift
```
Cannot find type 'DragDelegate' in scope
```
It still runs but any attempt to drag any snapshot file results in the error dialog box appearing.

**Comment by shaymanjohn** [comment]
> I'm actually getting an error on line 16 of EmulatorImageView.swift
> 
> ```
> Cannot find type 'DragDelegate' in scope
> ```
> 
> It still runs but any attempt to drag any snapshot file results in the error dialog box appearing.

That seems odd - can you see the DragDelegate protocol defined in Emulator.swift?

**Comment by hippietrail** [comment]
image
Looks right I think?

**Comment by shaymanjohn** [comment]
> image Looks right I think?

It does - so why the error saying not in scope?

**Comment by hippietrail** [comment]
Actually I just did a "Clean Build Folder" and that made the error go away but it still doesn't load files I drag and drop.

**Comment by shaymanjohn** [comment]
> Actually I just did a "Clean Build Folder" and that made the error go away but it still doesn't load files I drag and drop.

Some error logs might be good here, difficult for me to guess.
Does the path of the file (or name) you're dragging in have spaces in? That seems to be an issue. Can you try to drag a file in whose name and path doesn't contain spaces...

**Comment by shaymanjohn** [comment]
> > Actually I just did a "Clean Build Folder" and that made the error go away but it still doesn't load files I drag and drop.
> 
> Some error logs might be good here, difficult for me to guess. Does the path of the file (or name) you're dragging in have spaces in? That seems to be an issue. Can you try to drag a file in whose name and path doesn't contain spaces...

Pushed a fix for this to my branch on your repo (just need to encode the URL)

**Comment by hippietrail** [comment]
Ah you found it. I keep my Speccy games in a path with a space in the name of a folder. But I fixed it a different way:

In `Spectrum.swift` if we use `URL(fileURLWithPath:)` instead of `URL(string:)` that both takes care of the percent-encoding, and obviates the need to manually prefix `file://` to `filePath` in `EmulatorInputView.swift`.

Is this the correct way for me to communicate this or is there a git/GitHub feature? Or should I just amend my PR with both your changes and my changes to your changes? (-:

I'm not sure if I commented in the wrong place before: https://github.com/hippietrail/speccyMac/commit/08471c10e8d1e2bfa09e57ab9f3a9cf74e1ee0f2

**Comment by shaymanjohn** [comment]
> Ah you found it. I keep my Speccy games in a path with a space in the name of a folder. But I fixed it a different way:
> 
> In `Spectrum.swift` if we use `URL(fileURLWithPath:)` instead of `URL(string:)` that both takes care of the percent-encoding, and obviates the need to manually prefix `file://` to `filePath` in `EmulatorInputView.swift`.
> 
> Is this the correct way for me to communicate this or is there a git/GitHub feature? Or should I just amend my PR with both your changes and my changes to your changes? (-:
> 
> I'm not sure if I commented in the wrong place before: [hippietrail@08471c1](https://github.com/hippietrail/speccyMac/commit/08471c10e8d1e2bfa09e57ab9f3a9cf74e1ee0f2)

Ah nice, even better. Sounds good to me - amend your PR with all the changes 👍

**Pull request merged**
